<span title="Explaining tooltip">
<svg enable-background="new 45.6 168.9 504 504" id="Layer_1" version="1.1" viewBox="45.6 168.9 504 504" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><circle cx="297.6" cy="420.9" fill="#2196F3" r="225.4"/><rect fill="#FFFFFF" height="118.1" width="42.9" x="276.2" y="399.5"/><circle cx="297.6" cy="340.4" fill="#FFFFFF" r="26.8"/></svg>
公共變數
</span>