<h1>前台測試</h1>
<div class="nette-inner">
  <a href="debuglist.php?action=del" target="test">刪除檔案</a>
  <?php
  
    $handle = @fopen($_SERVER['DOCUMENT_ROOT'] . "/cache/output." . $_SESSION['UserID'] , "r");
    if ($handle) {
        while (($buffer = fgets($handle, 4096)) !== false) {
          if (is_file($_SERVER['DOCUMENT_ROOT'] . "/cache/" . trim($buffer). "." . $_SESSION['UserID'])) {
            echo '<pre><a href="debuglist.php?ccc='.trim($buffer).'" target="test">' . $buffer . '</a></pre>';
          } else {
            echo "<pre>" . $buffer . "</pre>";
          }

        }
        if (!feof($handle)) {
            // echo "Error: unexpected fgets() fail\n";
        }
        fclose($handle);
    }

  ?>
</div>